# Generated by Django 5.0 on 2024-02-19 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0003_recruiter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('title', models.CharField(max_length=20, null=True)),
                ('salary', models.FloatField()),
                ('image', models.FileField(upload_to='')),
                ('description', models.CharField(max_length=300, null=True)),
                ('experience', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=20)),
                ('skills', models.CharField(max_length=100)),
                ('creationdate', models.DateField()),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_app.recruiter')),
            ],
        ),
    ]
