# Generated by Django 5.0 on 2024-07-04 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_app', '0008_alter_job_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='image',
        ),
    ]
